#!/usr/bin/python3

import pandas as pd
import numpy as np
import argparse
import os



if __name__ == '__main__':
    
    parser = argparse.ArgumentParser(
        description='Generates an easy-to-visualize table of A3N vs A1N results grouped per map, strategy and #units'
    )

    parser.add_argument(
        'input', help='Raw .csv file as generated by analyse_a3n-vs-a1n.sh'
    )
    
    parser.add_argument(
        'output', help='The easy-to-visualize .csv output file to generate'
    )

    
    parser.add_argument(
        '-m', '--metric', required=False, choices=['wins','draws','losses','matches','score','%score'], 
        default='wins', 
        help='Which metric should appear in the output'
    )
    
    args = parser.parse_args()

    df = pd.read_csv(args.input)

    # builds a hierarchical (multiindex) data frame (kinda groups by map, strategy & units)
    hierarchical = df.set_index(['map', 'strategy', 'units']) 
    
    # displays only the 
    hierarchical.unstack(2)[args.metric].to_csv(args.output)


    

