#!/usr/bin/python3

import pandas as pd
import numpy as np
import argparse
import os


def generate_table(infile, outfile, metric):
    df = pd.read_csv(infile)

    # builds a hierarchical (multiindex) data frame (kinda groups by map, strategy & units)
    hierarchical = df.set_index(['map', 'strategy', 'units']) 
    
    # displays the results in appropriate format
    hierarchical.unstack(2)[metric].to_csv(outfile)


if __name__ == '__main__':
    
    parser = argparse.ArgumentParser(
        description='Generates an easy-to-visualize table of A3N vs A1N results grouped per map, strategy and #units'
    )

    parser.add_argument(
        'input', help='Raw .csv file as generated by analyse_a3n-vs-a1n.sh'
    )
    
    parser.add_argument(
        'output', help='The easy-to-visualize .csv output file to generate'
    )
    
    parser.add_argument(
        '-m', '--metric', required=False, choices=['wins','draws','losses','matches','score','%score'], 
        default='score', 
        help='Which metric should appear in the output'
    )
    
    args = parser.parse_args()
    
    generate_table(args.input, args.output, args.metric)

    


    

